// courses.js

const coursesData = [
    {
        id: 1,
        title: "មូលដ្ឋានអង់គ្លេស",
        category: "ភាសាអង់គ្លេស",
        type: 'free',
        instructor: "តេជគុណ ចាន់ណារិទ្ធ សំរិត",
        avatar: "https://placehold.co/40x40/3B82F6/FFFFFF?text=P",
        image: "basic-english.png",
        rating: 4.5,
        reviews: 120,
        price: "ឥតគិតថ្លៃ",
        lessons: 30,
        students: 20,
        duration: "៣ខែ",
        telegramLink: "​https://t.me/+QGlcHfLNbSY3ODll",
        overview: "វគ្គសិក្សានេះនឹងគ្របដណ្ដប់លើគ្រប់ទិដ្ឋភាពសំខាន់ៗនៃមូលដ្ឋានអង់គ្លេស...",
        curriculum: ["មេរៀនទី១៖ អក្ខរក្រម និងការស្វាគមន៍", "មេរៀនទី២៖ សព្វនាម និងកិរិយាស័ព្ទ 'To Be'", "មេរៀនទី៣៖ នាមឯកវចនៈ/ពហុវចនៈ"],
        instructor_bio: "ព្រះតេជគុណ ចាន់ណារិទ្ធ សំរិត បច្ចុប្បន្នកំពុងសិក្សាថ្នាក់បរិញ្ញាបត្រ។",
        benefits: ["យល់ដឹងស៊ីជម្រៅពីមូលដ្ឋានភាសា", "បង្កើនសមត្ថភាពអាន", "ត្រៀមខ្លួនបានល្អសម្រាប់ការសិក្សាកម្រិតខ្ពស់", "ការប្រឡង និងវិញ្ញាបនបត្រ"]
    },
    {
        id: 2,
        title: "វេយ្យាករណ៍ និងតែងសេចក្ដី",
        category: "ភាសាខ្មែរ",
        type: 'free',
        instructor: "លោក មាន បញ្ញា",
        avatar: "https://placehold.co/40x40/be123c/FFFFFF?text=K",
        image: "grammar-kh.png",
        rating: 4.8,
        reviews: 250,
        price: "ឥតគិតថ្លៃ",
        lessons: 25,
        students: 20,
        duration: "៣ខែ",
        telegramLink: "https://t.me/+GRVRIQaOf88zNWNl",
        overview: "ពង្រឹងមូលដ្ឋានគ្រឹះវេយ្យាករណ៍ និងរៀនពីបច្ចេកទេសសរសេរតែងសេចក្ដីឲ្យបានល្អ។",
        curriculum: ["មេរៀនទី១: ផ្នែកនៃពាក្យ", "មេរៀនទី២: រចនាសម្ព័ន្ធនៃល្បះ"],
        instructor_bio: "លោក មាន បញ្ញា បច្ចុប្បន្នជាអ្នកនិពន្ធមួយរូប",
        benefits: ["សរសេរតែងសេចក្ដីបានត្រឹមត្រូវតាមក្បួន", "យល់ច្បាស់ពីវេយ្យាករណ៍ខ្មែរ", "អាចប្រើប្រាស់ពាក្យពេចន៍បានល្អប្រសើរ", "ការប្រឡង និងវិញ្ញាបនបត្រ"]
    },
    {
        id: 3,
        title: "English II",
        category: "ភាសាអង់គ្លេស",
        type: 'free',
        instructor: "កញ្ញា ពៅ សុជាតា",
        avatar: "https://placehold.co/40x40/16a34a/FFFFFF?text=B",
        image: "english-ii.png",
        rating: 4.2,
        reviews: 95,
        price: "ឥតគិតថ្លៃ",
        lessons: 20,
        students: 20,
        duration: "៣ខែ",
        telegramLink: "https://t.me/+CmWt473P84RmNTk1",
        overview: "សិក្សាពីការប្រើប្រាស់ត្រឹមតែឃ្លាសាមញ្ញៗ ទៅជាអាចសន្ទនាដោយត្រង់ៗ និងងាយៗអំពីជីវិតប្រចាំថ្ងៃបាន",
        curriculum: ["ជាក់ស្ដែង"],
        instructor_bio: "កញ្ញា ពៅ សុជាតា បច្ចុប្បន្នកំពុងសិក្សាថ្នាក់បរិញ្ញាបត្រ។",
        benefits: ["Vocabulary", "Grammar", "Speaking and Listening", " Exam and Certificat"]
    }
];
